services:
  - type: web
    name: car-price-predictor-ml
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn application:app
    pythonVersion: 3.10.13
